server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
code:
  walker: uploads
api:
  prefix: ${API_PREFIX}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}