# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.disable-swagger-default-url=true

# Additional Swagger Configuration
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
springdoc.packages-to-scan=com.example.news.controllers
springdoc.paths-to-match=/api/**
springdoc.show-actuator=false
springdoc.show-springfox=false 